"""empty message

Revision ID: 23a1f4212663
Revises: 4dad859a06bc
Create Date: 2018-06-27 17:11:36.939633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a1f4212663'
down_revision = '4dad859a06bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('front_user', sa.Column('realname', sa.String(length=50), nullable=True))
    op.add_column('front_user', sa.Column('singature', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'singature')
    op.drop_column('front_user', 'realname')
    op.drop_column('front_user', 'gender')
    # ### end Alembic commands ###
