"""empty message

Revision ID: 4dad859a06bc
Revises: d50b0b1fa3a4
Create Date: 2018-06-26 14:15:19.144584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dad859a06bc'
down_revision = 'd50b0b1fa3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comment_num')
    # ### end Alembic commands ###
