"""empty message

Revision ID: 4f915cae0295
Revises: df976b76c1ee
Create Date: 2018-06-27 17:28:00.348823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f915cae0295'
down_revision = 'df976b76c1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'front_user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_2', 'post', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###
