"""empty message

Revision ID: 9802c8ee025e
Revises: 9a3895827858
Create Date: 2018-06-25 19:20:36.787000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9802c8ee025e'
down_revision = '9a3895827858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hits')
    # ### end Alembic commands ###
