"""empty message

Revision ID: 9969d2ce3c0b
Revises: f99d8e12cf9d
Create Date: 2018-06-25 17:43:56.812447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9969d2ce3c0b'
down_revision = 'f99d8e12cf9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'userprofile', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofile', type_='unique')
    # ### end Alembic commands ###
