"""empty message

Revision ID: 99eb041a1b9c
Revises: 9969d2ce3c0b
Create Date: 2018-06-25 19:05:15.188299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eb041a1b9c'
down_revision = '9969d2ce3c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hits')
    # ### end Alembic commands ###
