"""empty message

Revision ID: 9ebb28dfa820
Revises: 9802c8ee025e
Create Date: 2018-06-25 19:29:44.427950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ebb28dfa820'
down_revision = '9802c8ee025e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hit', sa.Integer(), nullable=True))
    op.drop_column('post', 'hits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('post', 'hit')
    # ### end Alembic commands ###
