"""empty message

Revision ID: 9a3895827858
Revises: 99eb041a1b9c
Create Date: 2018-06-25 19:15:04.153223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3895827858'
down_revision = '99eb041a1b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hits')
    # ### end Alembic commands ###
