"""empty message

Revision ID: b2ee5fa44bf8
Revises: 6516e0fb65d5
Create Date: 2018-06-25 19:56:53.221394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ee5fa44bf8'
down_revision = '6516e0fb65d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('highlight_post_ibfk_1', 'highlight_post', type_='foreignkey')
    op.create_foreign_key(None, 'highlight_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highlight_post', type_='foreignkey')
    op.create_foreign_key('highlight_post_ibfk_1', 'highlight_post', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
