"""empty message

Revision ID: d50b0b1fa3a4
Revises: b2ee5fa44bf8
Create Date: 2018-06-26 10:09:19.727793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50b0b1fa3a4'
down_revision = 'b2ee5fa44bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userprofile_ibfk_1', 'userprofile', type_='foreignkey')
    op.create_foreign_key(None, 'userprofile', 'front_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.create_foreign_key('userprofile_ibfk_1', 'userprofile', 'front_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
